### ISSUE TITLE
make command defaults to downloading counties

### ISSUE THREAD

**Issue by thomas-hervey** [fitnr/get-tiger#1]
This seems like a great tool. Because of the (Seemingly fickle) nature of census API and FTP sites, I wasn't able to download anything. I kept getting 425 errors when curling. Also, it seems like make commands switch to `2015/COUNTY/cb_2015_us_county_20m.zip ftp://ftp2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_20m.zip` regardless of what is entered.

Perhaps I am doing something wrong?
Thanks

**Comment by fitnr** [comment]
So there are two errors:
* 425 errors when curling
* downloading the counties data

The counties data is useful for downloading certain files, but it also comes with the repo. I've fixed the reorganizing slightly.

I haven't seen 425 errors, so I'm going to chalk it up to a passing problem. The Census's servers aren't perfect, and they do error out. If you still experience the problem, please reopen the issue with the terminal commands and output.
