### ISSUE TITLE
What is a key.ini?

### ISSUE THREAD

**Issue by waterlily10** [fitnr/get-tiger#2]
Hello fitnr, thank you for sharing "get-tiger". I'm sure it's the tool that I need to download census TIGER Line shapefiles, but it seems "make" doesn't work for me. 
I follow the instructions for OS X users: "install make with: xcode-select --install. For GDAL, install Homebrew and run: brew install gdal." I also use "gh repo clone fitnr/get-tiger" to download the repo and put the contents in the folder I would like to fill with GIS data. 
However, when I run "make", it reports: "Makefile:12: key.ini: No such file or directory make: *** No rule to make target `key.ini'.  Stop." 
I cannot find a file of "key.ini" in the repo but the Makefile mentions it. I do have a census API key with me. Could you please share the key.ini or the way to prepare the file? Thanks!

**Comment by fitnr** [comment]
Key.ini is a file that was formerly needed when this repo also read from the census API. I removed that set of code, but apparently left in a reference to the file. I'll push an update that removes the requirement
