### ISSUE TITLE
"make" works but still cannot download data sets

### ISSUE THREAD

**Issue by waterlily10** [fitnr/get-tiger#3]
Hello! Thank you for your swift response. Now "make"  and "make -f ini.mk YEAR=2020" work, but I still cannot download the data sets. Here below, I list the commands and the error messages for your reference.

make

> Available data sets:
> (run with "make DATASET")
> NATION - United States
> DIVISION - four very broad sections of the country
> REGION - nine broad sections of the country
> AIANNH - American Indian areas, Alaska Native areas, Hawaiian home lands
> AITSN - American Indian tribal subvidisions
> ANRC - Alaska Native regional corporations
> BG - Block groups
> CNECTA - Combined New England city and town areas
> CBSA - Core-based statistical qreas
> CD - Congressional districts 
> CONCITY - Consolidated cities 
> COUNTY - Counties
> COUNTY_WITHIN_UA - Urban areas segmented by county
> COUSUB - County subvidisions
> CSA - Consolidated statistical areas
> ELSD - Elementary school districts
> ESTATE - Estates [US Virgin Islands]
> METDIV - Metropolitan Divisions
> MIL - Military areas
> NECTA - New England city and town areas
> NECTADIV - New England city and town area divisions
> PLACE - Places
> PRIMARYROADS - Primary roads [national]
> PRISECROADS - Primary and secondary roads [by state]
> PUMA - Public use microdata areas
> RAILS - Railroads
> ROADS - Roads. Downloads one file for each county, then combines into state files.
> SCSD - Secondary school districts 
> SLDL - State legislative districts [lower chamber]
> SLDU - State legislative districts [upper chamber]
> STATE - States and territories
> SUBBARRIO - Sub-barrios [Puerto Rico]
> TABBLOCK - Blocks
> TBG - Tribal block groups
> TRACT - Census tracts
> TTRACT - Tribal Census tracts
> UAC - Urbanized areas
> UNSD - Unified school districts
> ZCTA5 - Zip code tabulation areas
> AREAWATER - Water polygons. Downloads one file for each county, then combines into state files.
> LINEARWATER - Water lines. Downloads one file for each county, then combines into state files.
> default year is 2019

make NATION STATE

> curl -Lo 2019/NATION/cb_2019_us_nation_5m.zip -sS --retry 10 --retry-delay 1 --connect-timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/NATION/cb_2019_us_nation_5m.zip
> curl: (28) Operation timed out after 2000 milliseconds with 0 out of 0 bytes received
> make: *** [2019/NATION/cb_2019_us_nation_5m.zip] Error 28

make COUNTY TRACT

> curl -Lo 2019/cb_2019_us_county_500k.zip -sS --retry 10 --retry-delay 1 --connect-timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_county_500k.zip
> curl: (28) Operation timed out after 2001 milliseconds with 0 out of 0 bytes received
> make: *** [2019/cb_2019_us_county_500k.zip] Error 28

make PLACE

> curl -Lo 2019/cb_2019_01_place_500k.zip -sS --retry 10 --retry-delay 1 --connect-timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_01_place_500k.zip
> curl: (28) Operation timed out after 2001 milliseconds with 0 out of 0 bytes received
> make: *** [2019/cb_2019_01_place_500k.zip] Error 28

make TRACT CARTOGRAPHIC=false

> mkdir -p 2019/TRACT
> curl -Lo 2019/TRACT/tl_2019_01_tract.zip -sS --retry 10 --retry-delay 1 --connect-timeout 2 ftp://ftp2.census.gov/geo/tiger/TIGER2019/TRACT/tl_2019_01_tract.zip
> curl: (28) Operation timed out after 2004 milliseconds with 0 out of 0 bytes received
> make: *** [2019/TRACT/tl_2019_01_tract.zip] Error 28

make -f ini.mk YEAR=2020

> mkdir -p 2020/COUNTY
> curl -Lo 2020/COUNTY/2020_Gaz_counties_national.zip ftp://ftp2.census.gov/geo/docs/maps-data/data/gazetteer/2020_Gazetteer/2020_Gaz_counties_national.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  138k  100  138k    0     0  20074      0  0:00:07  0:00:07 --:--:-- 30389
> unzip -p 2020/COUNTY/2020_Gaz_counties_national.zip | \
> 	iconv -f Windows-1252 -t UTF-8 | tail -n+2 | cut -f 2 | \
> 	awk '{ arr[substr($1, 1, 2)] = arr[substr($1, 1, 2)] FS substr($1, 3) } END \
> 	  {for (i in arr) {print "COUNTIES_" i " ="arr[i] } }' | \
> 	sort > counties/2020.ini

make 2013/BG.shp YEAR=2013

> make: *** No rule to make target `2013/BG.shp'.  Stop.

As the file of cb_2019_us_nation_5m.zip can be downloaded manually from  ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_nation_5m.zip,
I was thinking the error could be due to a change in FTP address, so I tried to make changes in the Makefile, e.g., from

> NATION   := NATION/cb_$(YEAR)_us_nation_5m.zip

into 

> NATION   := cb_$(YEAR)_us_nation_5m.zip

, and then run: make NATION STATE. However, I receive 

> curl -Lo 2019/cb_2019_us_nation_5m.zip -sS --retry 10 --retry-delay 1 --connect-timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_nation_5m.zip
> curl: (28) Operation timed out after 2002 milliseconds with 0 out of 0 bytes received
> make: *** [2019/cb_2019_us_nation_5m.zip] Error 28

Could you kindly check? Many thanks!

**Comment by fitnr** [comment]
```
curl: (28) Operation timed out after 2001 milliseconds with 0 out of 0 bytes received
```
This is an error from `curl` telling you that it can't connect to the census website. Check your internet connection and proxy settings. The census servers also suffer outages every once in a while.

```
make 2013/BG.shp YEAR=2013
make: *** No rule to make target `2013/BG.shp'. Stop.
```

The 2013 config file isn't part of the repo. If you want to create it use the command `make -f ini.mk YEAR=2013`. I've updated  that command in the README.

**Comment by westlily1202** [comment]
make NATION STATE

> mkdir -p 2019/NATION
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_nation_5m.zip -o 2019/NATION/cb_2019_us_nation_5m.zip
> make: wget: No such file or directory
> make: *** [2019/NATION/cb_2019_us_nation_5m.zip] Error 1

Where should I install "wget"?

**Comment by waterlily10** [comment]
Thank you so much! I've made much progress. Still, I have three issues.

1. I cannot download data for the years before 2014. Here below, I give examples for the years of 2013 and 2010. The error for the year 2013 could be due to no shp folder under ftp://ftp2.census.gov/geo/tiger/GENZ2013.

make STATE YEAR=2013

> mkdir -p 2013
> mkdir -p 2013/STATE
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2013/shp/cb_2013_us_state_500k.zip -o 2013/STATE/cb_2013_us_state_500k.zip
> make: *** [2013/STATE/cb_2013_us_state_500k.zip] Error 8

make -f ini.mk YEAR=2013

> mkdir -p 2013/COUNTY
> curl -Lo 2013/COUNTY/2013_Gaz_counties_national.zip ftp://ftp2.census.gov/geo/docs/maps-data/data/gazetteer/2013_Gazetteer/2013_Gaz_counties_national.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  142k  100  142k    0     0  20000      0  0:00:07  0:00:07 --:--:-- 31322
> unzip -p 2013/COUNTY/2013_Gaz_counties_national.zip | \
> 	iconv -f Windows-1252 -t UTF-8 | tail -n+2 | cut -f 2 | \
> 	awk '{ arr[substr($1, 1, 2)] = arr[substr($1, 1, 2)] FS substr($1, 3) } END \
> 	  {for (i in arr) {print "COUNTIES_" i " ="arr[i] } }' | \
> 	sort > counties/2013.ini

make 2013/BG.shp YEAR=2013

> mkdir -p 2013/BG
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2013/shp/cb_2013_01_bg_500k.zip -o 2013/BG/cb_2013_01_bg_500k.zip
> make: *** [2013/BG/cb_2013_01_bg_500k.zip] Error 8

Another example. Changing the year of 2010 to 2014 doesn't work either.

make -f ini.mk YEAR=2010

> mkdir -p 2010/COUNTY
> curl -Lo 2010/COUNTY/2010_Gaz_counties_national.zip ftp://ftp2.census.gov/geo/docs/maps-data/data/gazetteer/2010_Gazetteer/2010_Gaz_counties_national.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0^R
>   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
> curl: (9) Server denied you to change to the given directory
> make: *** [2010/COUNTY/2010_Gaz_counties_national.zip] Error 9

make 2010/ROADS.shp YEAR=2010 

> make: *** No rule to make target `2010/ROADS.shp'.  Stop.

2. "\<year\>/\<NAME\>.shp" works for the year 2014, but I got an error message in the end. Moreover, I find all the downloads in my "get-tiger" folder, which can be opened. I do find zip files of the same names in the folder "./get-tiger/2014", however, they all have zero byte. 

make 2014/BG.shp YEAR=2014

> mkdir -p 2014/BG
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_01_bg_500k.zip -o 2014/BG/cb_2014_01_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_02_bg_500k.zip -o 2014/BG/cb_2014_02_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_04_bg_500k.zip -o 2014/BG/cb_2014_04_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_05_bg_500k.zip -o 2014/BG/cb_2014_05_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_06_bg_500k.zip -o 2014/BG/cb_2014_06_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_08_bg_500k.zip -o 2014/BG/cb_2014_08_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_09_bg_500k.zip -o 2014/BG/cb_2014_09_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_10_bg_500k.zip -o 2014/BG/cb_2014_10_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_11_bg_500k.zip -o 2014/BG/cb_2014_11_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_12_bg_500k.zip -o 2014/BG/cb_2014_12_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_13_bg_500k.zip -o 2014/BG/cb_2014_13_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_15_bg_500k.zip -o 2014/BG/cb_2014_15_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_16_bg_500k.zip -o 2014/BG/cb_2014_16_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_17_bg_500k.zip -o 2014/BG/cb_2014_17_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_18_bg_500k.zip -o 2014/BG/cb_2014_18_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_19_bg_500k.zip -o 2014/BG/cb_2014_19_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_20_bg_500k.zip -o 2014/BG/cb_2014_20_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_21_bg_500k.zip -o 2014/BG/cb_2014_21_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_22_bg_500k.zip -o 2014/BG/cb_2014_22_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_23_bg_500k.zip -o 2014/BG/cb_2014_23_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_24_bg_500k.zip -o 2014/BG/cb_2014_24_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_25_bg_500k.zip -o 2014/BG/cb_2014_25_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_26_bg_500k.zip -o 2014/BG/cb_2014_26_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_27_bg_500k.zip -o 2014/BG/cb_2014_27_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_28_bg_500k.zip -o 2014/BG/cb_2014_28_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_29_bg_500k.zip -o 2014/BG/cb_2014_29_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_30_bg_500k.zip -o 2014/BG/cb_2014_30_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_31_bg_500k.zip -o 2014/BG/cb_2014_31_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_32_bg_500k.zip -o 2014/BG/cb_2014_32_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_33_bg_500k.zip -o 2014/BG/cb_2014_33_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_34_bg_500k.zip -o 2014/BG/cb_2014_34_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_35_bg_500k.zip -o 2014/BG/cb_2014_35_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_36_bg_500k.zip -o 2014/BG/cb_2014_36_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_37_bg_500k.zip -o 2014/BG/cb_2014_37_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_38_bg_500k.zip -o 2014/BG/cb_2014_38_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_39_bg_500k.zip -o 2014/BG/cb_2014_39_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_40_bg_500k.zip -o 2014/BG/cb_2014_40_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_41_bg_500k.zip -o 2014/BG/cb_2014_41_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_42_bg_500k.zip -o 2014/BG/cb_2014_42_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_44_bg_500k.zip -o 2014/BG/cb_2014_44_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_45_bg_500k.zip -o 2014/BG/cb_2014_45_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_46_bg_500k.zip -o 2014/BG/cb_2014_46_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_47_bg_500k.zip -o 2014/BG/cb_2014_47_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_48_bg_500k.zip -o 2014/BG/cb_2014_48_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_49_bg_500k.zip -o 2014/BG/cb_2014_49_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_50_bg_500k.zip -o 2014/BG/cb_2014_50_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_51_bg_500k.zip -o 2014/BG/cb_2014_51_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_53_bg_500k.zip -o 2014/BG/cb_2014_53_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_54_bg_500k.zip -o 2014/BG/cb_2014_54_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_55_bg_500k.zip -o 2014/BG/cb_2014_55_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_56_bg_500k.zip -o 2014/BG/cb_2014_56_bg_500k.zip
> wget -q -nc -t 10 --waitretry 1 --timeout 2 ftp://ftp2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_72_bg_500k.zip -o 2014/BG/cb_2014_72_bg_500k.zip
> ogrmerge.py -f 'ESRI Shapefile' -overwrite_ds -single -o 2014/BG.shp /vsizip/2014/BG/cb_2014_01_bg_500k.zip/cb_2014_01_bg_500k.shp /vsizip/2014/BG/cb_2014_02_bg_500k.zip/cb_2014_02_bg_500k.shp /vsizip/2014/BG/cb_2014_04_bg_500k.zip/cb_2014_04_bg_500k.shp /vsizip/2014/BG/cb_2014_05_bg_500k.zip/cb_2014_05_bg_500k.shp /vsizip/2014/BG/cb_2014_06_bg_500k.zip/cb_2014_06_bg_500k.shp /vsizip/2014/BG/cb_2014_08_bg_500k.zip/cb_2014_08_bg_500k.shp /vsizip/2014/BG/cb_2014_09_bg_500k.zip/cb_2014_09_bg_500k.shp /vsizip/2014/BG/cb_2014_10_bg_500k.zip/cb_2014_10_bg_500k.shp /vsizip/2014/BG/cb_2014_11_bg_500k.zip/cb_2014_11_bg_500k.shp /vsizip/2014/BG/cb_2014_12_bg_500k.zip/cb_2014_12_bg_500k.shp /vsizip/2014/BG/cb_2014_13_bg_500k.zip/cb_2014_13_bg_500k.shp /vsizip/2014/BG/cb_2014_15_bg_500k.zip/cb_2014_15_bg_500k.shp /vsizip/2014/BG/cb_2014_16_bg_500k.zip/cb_2014_16_bg_500k.shp /vsizip/2014/BG/cb_2014_17_bg_500k.zip/cb_2014_17_bg_500k.shp /vsizip/2014/BG/cb_2014_18_bg_500k.zip/cb_2014_18_bg_500k.shp /vsizip/2014/BG/cb_2014_19_bg_500k.zip/cb_2014_19_bg_500k.shp /vsizip/2014/BG/cb_2014_20_bg_500k.zip/cb_2014_20_bg_500k.shp /vsizip/2014/BG/cb_2014_21_bg_500k.zip/cb_2014_21_bg_500k.shp /vsizip/2014/BG/cb_2014_22_bg_500k.zip/cb_2014_22_bg_500k.shp /vsizip/2014/BG/cb_2014_23_bg_500k.zip/cb_2014_23_bg_500k.shp /vsizip/2014/BG/cb_2014_24_bg_500k.zip/cb_2014_24_bg_500k.shp /vsizip/2014/BG/cb_2014_25_bg_500k.zip/cb_2014_25_bg_500k.shp /vsizip/2014/BG/cb_2014_26_bg_500k.zip/cb_2014_26_bg_500k.shp /vsizip/2014/BG/cb_2014_27_bg_500k.zip/cb_2014_27_bg_500k.shp /vsizip/2014/BG/cb_2014_28_bg_500k.zip/cb_2014_28_bg_500k.shp /vsizip/2014/BG/cb_2014_29_bg_500k.zip/cb_2014_29_bg_500k.shp /vsizip/2014/BG/cb_2014_30_bg_500k.zip/cb_2014_30_bg_500k.shp /vsizip/2014/BG/cb_2014_31_bg_500k.zip/cb_2014_31_bg_500k.shp /vsizip/2014/BG/cb_2014_32_bg_500k.zip/cb_2014_32_bg_500k.shp /vsizip/2014/BG/cb_2014_33_bg_500k.zip/cb_2014_33_bg_500k.shp /vsizip/2014/BG/cb_2014_34_bg_500k.zip/cb_2014_34_bg_500k.shp /vsizip/2014/BG/cb_2014_35_bg_500k.zip/cb_2014_35_bg_500k.shp /vsizip/2014/BG/cb_2014_36_bg_500k.zip/cb_2014_36_bg_500k.shp /vsizip/2014/BG/cb_2014_37_bg_500k.zip/cb_2014_37_bg_500k.shp /vsizip/2014/BG/cb_2014_38_bg_500k.zip/cb_2014_38_bg_500k.shp /vsizip/2014/BG/cb_2014_39_bg_500k.zip/cb_2014_39_bg_500k.shp /vsizip/2014/BG/cb_2014_40_bg_500k.zip/cb_2014_40_bg_500k.shp /vsizip/2014/BG/cb_2014_41_bg_500k.zip/cb_2014_41_bg_500k.shp /vsizip/2014/BG/cb_2014_42_bg_500k.zip/cb_2014_42_bg_500k.shp /vsizip/2014/BG/cb_2014_44_bg_500k.zip/cb_2014_44_bg_500k.shp /vsizip/2014/BG/cb_2014_45_bg_500k.zip/cb_2014_45_bg_500k.shp /vsizip/2014/BG/cb_2014_46_bg_500k.zip/cb_2014_46_bg_500k.shp /vsizip/2014/BG/cb_2014_47_bg_500k.zip/cb_2014_47_bg_500k.shp /vsizip/2014/BG/cb_2014_48_bg_500k.zip/cb_2014_48_bg_500k.shp /vsizip/2014/BG/cb_2014_49_bg_500k.zip/cb_2014_49_bg_500k.shp /vsizip/2014/BG/cb_2014_50_bg_500k.zip/cb_2014_50_bg_500k.shp /vsizip/2014/BG/cb_2014_51_bg_500k.zip/cb_2014_51_bg_500k.shp /vsizip/2014/BG/cb_2014_53_bg_500k.zip/cb_2014_53_bg_500k.shp /vsizip/2014/BG/cb_2014_54_bg_500k.zip/cb_2014_54_bg_500k.shp /vsizip/2014/BG/cb_2014_55_bg_500k.zip/cb_2014_55_bg_500k.shp /vsizip/2014/BG/cb_2014_56_bg_500k.zip/cb_2014_56_bg_500k.shp /vsizip/2014/BG/cb_2014_72_bg_500k.zip/cb_2014_72_bg_500k.shp
> ERROR: Cannot open /vsizip/2014/BG/cb_2014_01_bg_500k.zip/cb_2014_01_bg_500k.shp
> make: *** [2014/BG.shp] Error 1

3. I would like to download TIGER/Line files for specific geographical types for the year 2010 by setting CARTOGRAPHIC=false. The commands work for AREAWATER but not for RAILS and ROADS.

make 2010/RAILS.shp YEAR=2010 CARTOGRAPHIC=false

>make: *** No rule to make target `2010/RAILS.shp'.  Stop.

make 2010/ROADS.shp YEAR=2010 CARTOGRAPHIC=false

>make: *** No rule to make target `2010/ROADS.shp'.  Stop.

However, "make 2010/AREAWATER.shp YEAR=2010 CARTOGRAPHIC=false" can download files.

**Comment by fitnr** [comment]
```
 ERROR: Cannot open /vsizip/2014/BG/cb_2014_01_bg_500k.zip/cb_2014_01_bg_500k.shp
make: *** [2014/BG.shp] Error 1
```
There was a bug in the wget command, so the download files went to the wrong directory. I've fixed. The zip files should be in the main directory you're working in. If you move them to `2014/BG`, you should be able to rerun the command.

```
make 2010/RAILS.shp YEAR=2010 CARTOGRAPHIC=false
make 2010/ROADS.shp YEAR=2010 CARTOGRAPHIC=false
```
The "secret bonus tasks" for merging data aren't available for all datasets. But since you're interested, I've added ROADS and RAILS.
